#!/bin/sh
uci set system.@system[0].hostname=MyRouter
uci commit system
BSSID=`ifconfig | grep wlan0 | awk '{print $5}' | head -n1 | tr -d :`
uci set wireless.@wifi-iface[0].ssid="mywifi-$BSSID"
uci commit wireless
exit 0
